language: java
jdk: oraclejdk9
deploy:
  provider: cloudfoundry
  username: karrthicks10@gmail.com
  password: $DEPLOY_TOKEN
  api: https://api.run.pivotal.io
  organization: citiipay
  space: development
  manifest: manifest.yml
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install
